export const COUNTRIES = [
  { code: "IT", name: "Italia", flag: "🇮🇹" },
  { code: "FR", name: "Francia", flag: "🇫🇷" },
  { code: "DE", name: "Germania", flag: "🇩🇪" },
  { code: "ES", name: "Spagna", flag: "🇪🇸" },
  { code: "PT", name: "Portogallo", flag: "🇵🇹" },
  { code: "CH", name: "Svizzera", flag: "🇨🇭" },
  { code: "AT", name: "Austria", flag: "🇦🇹" },
  { code: "BE", name: "Belgio", flag: "🇧🇪" },
  { code: "NL", name: "Paesi Bassi", flag: "🇳🇱" },
  { code: "SE", name: "Svezia", flag: "🇸🇪" },
  { code: "GB", name: "Regno Unito", flag: "🇬🇧" },
  { code: "IE", name: "Irlanda", flag: "🇮🇪" },
  { code: "US", name: "Stati Uniti", flag: "🇺🇸" },
  { code: "CA", name: "Canada", flag: "🇨🇦" },
  { code: "AU", name: "Australia", flag: "🇦🇺" },
  { code: "MA", name: "Marocco", flag: "🇲🇦" },
  { code: "DZ", name: "Algeria", flag: "🇩🇿" },
  { code: "TN", name: "Tunisia", flag: "🇹🇳" },
  { code: "EG", name: "Egitto", flag: "🇪🇬" },
  { code: "SN", name: "Senegal", flag: "🇸🇳" },
  { code: "NG", name: "Nigeria", flag: "🇳🇬" },
  { code: "GH", name: "Ghana", flag: "🇬🇭" },
  { code: "KE", name: "Kenya", flag: "🇰🇪" },
  { code: "BD", name: "Bangladesh", flag: "🇧🇩" },
  { code: "PK", name: "Pakistan", flag: "🇵🇰" },
  { code: "IN", name: "India", flag: "🇮🇳" },
  { code: "CN", name: "Cina", flag: "🇨🇳" },
  { code: "UA", name: "Ucraina", flag: "🇺🇦" },
  { code: "RU", name: "Russia", flag: "🇷🇺" },
  { code: "TR", name: "Turchia", flag: "🇹🇷" },
  { code: "BR", name: "Brasile", flag: "🇧🇷" },
  { code: "AR", name: "Argentina", flag: "🇦🇷" },
  { code: "CO", name: "Colombia", flag: "🇨🇴" },
  { code: "VE", name: "Venezuela", flag: "🇻🇪" },
  { code: "PH", name: "Filippine", flag: "🇵🇭" },
  { code: "SV", name: "El Salvador", flag: "🇸🇻" },
  { code: "HN", name: "Honduras", flag: "🇭🇳" },
  { code: "GT", name: "Guatemala", flag: "🇬🇹" },
  { code: "MX", name: "Messico", flag: "🇲🇽" },
  { code: "ZA", name: "Sudafrica", flag: "🇿🇦" },
  { code: "KR", name: "Corea del Sud", flag: "🇰🇷" },
  { code: "JP", name: "Giappone", flag: "🇯🇵" },
  { code: "NO", name: "Norvegia", flag: "🇳🇴" },
  { code: "DK", name: "Danimarca", flag: "🇩🇰" },
  { code: "FI", name: "Finlandia", flag: "🇫🇮" },
  { code: "PL", name: "Polonia", flag: "🇵🇱" },
  { code: "CZ", name: "Repubblica Ceca", flag: "🇨🇿" },
  { code: "HU", name: "Ungheria", flag: "🇭🇺" },
  { code: "RO", name: "Romania", flag: "🇷🇴" },
  { code: "BG", name: "Bulgaria", flag: "🇧🇬" },
  { code: "GR", name: "Grecia", flag: "🇬🇷" },
  { code: "HR", name: "Croazia", flag: "🇭🇷" },
  { code: "RS", name: "Serbia", flag: "🇷🇸" },
  { code: "AL", name: "Albania", flag: "🇦🇱" },
  { code: "MD", name: "Moldavia", flag: "🇲🇩" },
  { code: "BY", name: "Bielorussia", flag: "🇧🇾" },
  { code: "KG", name: "Kirghizistan", flag: "🇰🇬" },
  { code: "UZ", name: "Uzbekistan", flag: "🇺🇿" },
  { code: "KZ", name: "Kazakistan", flag: "🇰🇿" },
  { code: "IR", name: "Iran", flag: "🇮🇷" },
  { code: "IQ", name: "Iraq", flag: "🇮🇶" },
  { code: "SY", name: "Siria", flag: "🇸🇾" },
  { code: "SO", name: "Somalia", flag: "🇸🇴" },
  { code: "AF", name: "Afghanistan", flag: "🇦🇫" },
  { code: "MM", name: "Myanmar", flag: "🇲🇲" },
  { code: "VN", name: "Vietnam", flag: "🇻🇳" },
  { code: "LA", name: "Laos", flag: "🇱🇦" },
  { code: "KH", name: "Cambogia", flag: "🇰🇭" },
  { code: "ID", name: "Indonesia", flag: "🇮🇩" },
  { code: "MY", name: "Malesia", flag: "🇲🇾" },
  { code: "TH", name: "Thailandia", flag: "🇹🇭" },
  { code: "LK", name: "Sri Lanka", flag: "🇱🇰" },
  { code: "NP", name: "Nepal", flag: "🇳🇵" },
  { code: "BT", name: "Bhutan", flag: "🇧🇹" },
  { code: "MN", name: "Mongolia", flag: "🇲🇳" },
  { code: "NZ", name: "Nuova Zelanda", flag: "🇳🇿" },
  { code: "CL", name: "Cile", flag: "🇨🇱" },
  { code: "PE", name: "Perù", flag: "🇵🇪" },
  { code: "EC", name: "Ecuador", flag: "🇪🇨" },
  { code: "UY", name: "Uruguay", flag: "🇺🇾" },
  { code: "PY", name: "Paraguay", flag: "🇵🇾" },
  { code: "BO", name: "Bolivia", flag: "🇧🇴" },
  { code: "GY", name: "Guyana", flag: "🇬🇾" },
  { code: "SR", name: "Suriname", flag: "🇸🇷" },
  { code: "TT", name: "Trinidad e Tobago", flag: "🇹🇹" },
];

export const SITUATIONS = [
  { value: "lavoro", it: "💼 Lavoro", en: "💼 Work", fr: "💼 Travail", es: "💼 Trabajo", ar: "💼 عمل" },
  { value: "studio", it: "🎓 Studio", en: "🎓 Study", fr: "🎓 Études", es: "🎓 Estudio", ar: "🎓 دراسة" },
  { value: "famiglia", it: "👨‍👩‍👧 Famiglia", en: "👨‍👩‍👧 Family", fr: "👨‍👩‍👧 Famille", es: "👨‍👩‍👧 Familia", ar: "👨‍👩‍👧 لم شمل" },
  { value: "rinnovo", it: "🔄 Rinnovo", en: "🔄 Renewal", fr: "🔄 Renouvellement", es: "🔄 Renovación", ar: "🔄 تجديد" },
  { value: "altro", it: "ℹ️ Altro", en: "ℹ️ Other", fr: "ℹ️ Autre", es: "ℹ️ Otro", ar: "ℹ️ آخر" },
];