// NOTA: COUNTRIES copre i 195 paesi riconosciuti (193 Stati membri ONU +
// Palestina + Santa Sede/Vaticano). Codici ISO 3166-1 alpha-2. I paesi senza
// procedure restano selezionabili ma con status "unavailable" (vedi
// lib/db/procedures/_registry.ts).

export const COUNTRIES = [
  // ── Europa Occidentale / meridionale ──
  { code: "IT", it: "Italia", en: "Italy", flag: "🇮🇹" },
  { code: "FR", it: "Francia", en: "France", flag: "🇫🇷" },
  { code: "DE", it: "Germania", en: "Germany", flag: "🇩🇪" },
  { code: "ES", it: "Spagna", en: "Spain", flag: "🇪🇸" },
  { code: "PT", it: "Portogallo", en: "Portugal", flag: "🇵🇹" },
  { code: "CH", it: "Svizzera", en: "Switzerland", flag: "🇨🇭" },
  { code: "AT", it: "Austria", en: "Austria", flag: "🇦🇹" },
  { code: "BE", it: "Belgio", en: "Belgium", flag: "🇧🇪" },
  { code: "NL", it: "Paesi Bassi", en: "Netherlands", flag: "🇳🇱" },
  { code: "LU", it: "Lussemburgo", en: "Luxembourg", flag: "🇱🇺" },
  { code: "LI", it: "Liechtenstein", en: "Liechtenstein", flag: "🇱🇮" },
  { code: "MC", it: "Monaco", en: "Monaco", flag: "🇲🇨" },
  { code: "AD", it: "Andorra", en: "Andorra", flag: "🇦🇩" },
  { code: "SM", it: "San Marino", en: "San Marino", flag: "🇸🇲" },
  { code: "VA", it: "Città del Vaticano", en: "Vatican City", flag: "🇻🇦" },
  { code: "MT", it: "Malta", en: "Malta", flag: "🇲🇹" },
  { code: "CY", it: "Cipro", en: "Cyprus", flag: "🇨🇾" },
  { code: "GR", it: "Grecia", en: "Greece", flag: "🇬🇷" },
  // ── Europa settentrionale ──
  { code: "SE", it: "Svezia", en: "Sweden", flag: "🇸🇪" },
  { code: "NO", it: "Norvegia", en: "Norway", flag: "🇳🇴" },
  { code: "DK", it: "Danimarca", en: "Denmark", flag: "🇩🇰" },
  { code: "FI", it: "Finlandia", en: "Finland", flag: "🇫🇮" },
  { code: "IS", it: "Islanda", en: "Iceland", flag: "🇮🇸" },
  { code: "IE", it: "Irlanda", en: "Ireland", flag: "🇮🇪" },
  { code: "GB", it: "Regno Unito", en: "United Kingdom", flag: "🇬🇧" },
  { code: "EE", it: "Estonia", en: "Estonia", flag: "🇪🇪" },
  { code: "LV", it: "Lettonia", en: "Latvia", flag: "🇱🇻" },
  { code: "LT", it: "Lituania", en: "Lithuania", flag: "🇱🇹" },
  // ── Europa orientale / centrale ──
  { code: "PL", it: "Polonia", en: "Poland", flag: "🇵🇱" },
  { code: "CZ", it: "Repubblica Ceca", en: "Czech Republic", flag: "🇨🇿" },
  { code: "SK", it: "Slovacchia", en: "Slovakia", flag: "🇸🇰" },
  { code: "HU", it: "Ungheria", en: "Hungary", flag: "🇭🇺" },
  { code: "RO", it: "Romania", en: "Romania", flag: "🇷🇴" },
  { code: "BG", it: "Bulgaria", en: "Bulgaria", flag: "🇧🇬" },
  { code: "SI", it: "Slovenia", en: "Slovenia", flag: "🇸🇮" },
  { code: "HR", it: "Croazia", en: "Croatia", flag: "🇭🇷" },
  { code: "RS", it: "Serbia", en: "Serbia", flag: "🇷🇸" },
  { code: "AL", it: "Albania", en: "Albania", flag: "🇦🇱" },
  { code: "MD", it: "Moldavia", en: "Moldova", flag: "🇲🇩" },
  { code: "BY", it: "Bielorussia", en: "Belarus", flag: "🇧🇾" },
  { code: "UA", it: "Ucraina", en: "Ukraine", flag: "🇺🇦" },
  { code: "RU", it: "Russia", en: "Russia", flag: "🇷🇺" },
  { code: "ME", it: "Montenegro", en: "Montenegro", flag: "🇲🇪" },
  { code: "MK", it: "Macedonia del Nord", en: "North Macedonia", flag: "🇲🇰" },
  { code: "BA", it: "Bosnia ed Erzegovina", en: "Bosnia and Herzegovina", flag: "🇧🇦" },
  { code: "XK", it: "Kosovo", en: "Kosovo", flag: "🇽🇰" },
  // ── Nord America ──
  { code: "US", it: "Stati Uniti", en: "United States", flag: "🇺🇸" },
  { code: "CA", it: "Canada", en: "Canada", flag: "🇨🇦" },
  { code: "MX", it: "Messico", en: "Mexico", flag: "🇲🇽" },
  // ── America centrale / Caraibi ──
  { code: "GT", it: "Guatemala", en: "Guatemala", flag: "🇬🇹" },
  { code: "BZ", it: "Belize", en: "Belize", flag: "🇧🇿" },
  { code: "SV", it: "El Salvador", en: "El Salvador", flag: "🇸🇻" },
  { code: "HN", it: "Honduras", en: "Honduras", flag: "🇭🇳" },
  { code: "NI", it: "Nicaragua", en: "Nicaragua", flag: "🇳🇮" },
  { code: "CR", it: "Costa Rica", en: "Costa Rica", flag: "🇨🇷" },
  { code: "PA", it: "Panama", en: "Panama", flag: "🇵🇦" },
  { code: "CU", it: "Cuba", en: "Cuba", flag: "🇨🇺" },
  { code: "HT", it: "Haiti", en: "Haiti", flag: "🇭🇹" },
  { code: "DO", it: "Repubblica Dominicana", en: "Dominican Republic", flag: "🇩🇴" },
  { code: "JM", it: "Giamaica", en: "Jamaica", flag: "🇯🇲" },
  { code: "TT", it: "Trinidad e Tobago", en: "Trinidad and Tobago", flag: "🇹🇹" },
  { code: "BB", it: "Barbados", en: "Barbados", flag: "🇧🇧" },
  { code: "BS", it: "Bahamas", en: "Bahamas", flag: "🇧🇸" },
  { code: "AG", it: "Antigua e Barbuda", en: "Antigua and Barbuda", flag: "🇦🇬" },
  { code: "DM", it: "Dominica", en: "Dominica", flag: "🇩🇲" },
  { code: "GD", it: "Grenada", en: "Grenada", flag: "🇬🇩" },
  { code: "KN", it: "Saint Kitts e Nevis", en: "Saint Kitts and Nevis", flag: "🇰🇳" },
  { code: "LC", it: "Saint Lucia", en: "Saint Lucia", flag: "🇱🇨" },
  { code: "VC", it: "Saint Vincent e Grenadine", en: "Saint Vincent and the Grenadines", flag: "🇻🇨" },
  // ── Sud America ──
  { code: "BR", it: "Brasile", en: "Brazil", flag: "🇧🇷" },
  { code: "AR", it: "Argentina", en: "Argentina", flag: "🇦🇷" },
  { code: "CO", it: "Colombia", en: "Colombia", flag: "🇨🇴" },
  { code: "VE", it: "Venezuela", en: "Venezuela", flag: "🇻🇪" },
  { code: "CL", it: "Cile", en: "Chile", flag: "🇨🇱" },
  { code: "PE", it: "Perù", en: "Peru", flag: "🇵🇪" },
  { code: "EC", it: "Ecuador", en: "Ecuador", flag: "🇪🇨" },
  { code: "BO", it: "Bolivia", en: "Bolivia", flag: "🇧🇴" },
  { code: "PY", it: "Paraguay", en: "Paraguay", flag: "🇵🇾" },
  { code: "UY", it: "Uruguay", en: "Uruguay", flag: "🇺🇾" },
  { code: "GY", it: "Guyana", en: "Guyana", flag: "🇬🇾" },
  { code: "SR", it: "Suriname", en: "Suriname", flag: "🇸🇷" },
  // ── Africa del Nord ──
  { code: "MA", it: "Marocco", en: "Morocco", flag: "🇲🇦" },
  { code: "DZ", it: "Algeria", en: "Algeria", flag: "🇩🇿" },
  { code: "TN", it: "Tunisia", en: "Tunisia", flag: "🇹🇳" },
  { code: "LY", it: "Libia", en: "Libya", flag: "🇱🇾" },
  { code: "EG", it: "Egitto", en: "Egypt", flag: "🇪🇬" },
  { code: "SD", it: "Sudan", en: "Sudan", flag: "🇸🇩" },
  // ── Africa occidentale ──
  { code: "SN", it: "Senegal", en: "Senegal", flag: "🇸🇳" },
  { code: "MR", it: "Mauritania", en: "Mauritania", flag: "🇲🇷" },
  { code: "ML", it: "Mali", en: "Mali", flag: "🇲🇱" },
  { code: "NE", it: "Niger", en: "Niger", flag: "🇳🇪" },
  { code: "TD", it: "Ciad", en: "Chad", flag: "🇹🇩" },
  { code: "CM", it: "Camerun", en: "Cameroon", flag: "🇨🇲" },
  { code: "NG", it: "Nigeria", en: "Nigeria", flag: "🇳🇬" },
  { code: "GH", it: "Ghana", en: "Ghana", flag: "🇬🇭" },
  { code: "CI", it: "Costa d'Avorio", en: "Ivory Coast", flag: "🇨🇮" },
  { code: "BF", it: "Burkina Faso", en: "Burkina Faso", flag: "🇧🇫" },
  { code: "TG", it: "Togo", en: "Togo", flag: "🇹🇬" },
  { code: "BJ", it: "Benin", en: "Benin", flag: "🇧🇯" },
  { code: "GN", it: "Guinea", en: "Guinea", flag: "🇬🇳" },
  { code: "GW", it: "Guinea-Bissau", en: "Guinea-Bissau", flag: "🇬🇼" },
  { code: "SL", it: "Sierra Leone", en: "Sierra Leone", flag: "🇸🇱" },
  { code: "LR", it: "Liberia", en: "Liberia", flag: "🇱🇷" },
  { code: "GM", it: "Gambia", en: "Gambia", flag: "🇬🇲" },
  { code: "CV", it: "Capo Verde", en: "Cape Verde", flag: "🇨🇻" },
  // ── Africa centrale ──
  { code: "CF", it: "Repubblica Centrafricana", en: "Central African Republic", flag: "🇨🇫" },
  { code: "GQ", it: "Guinea Equatoriale", en: "Equatorial Guinea", flag: "🇬🇶" },
  { code: "GA", it: "Gabon", en: "Gabon", flag: "🇬🇦" },
  { code: "CG", it: "Repubblica del Congo", en: "Republic of the Congo", flag: "🇨🇬" },
  { code: "CD", it: "RD del Congo", en: "DR Congo", flag: "🇨🇩" },
  { code: "ST", it: "São Tomé e Príncipe", en: "São Tomé and Príncipe", flag: "🇸🇹" },
  { code: "AO", it: "Angola", en: "Angola", flag: "🇦🇴" },
  { code: "ZM", it: "Zambia", en: "Zambia", flag: "🇿🇲" },
  // ── Africa orientale ──
  { code: "ET", it: "Etiopia", en: "Ethiopia", flag: "🇪🇹" },
  { code: "ER", it: "Eritrea", en: "Eritrea", flag: "🇪🇷" },
  { code: "DJ", it: "Gibuti", en: "Djibouti", flag: "🇩🇯" },
  { code: "SO", it: "Somalia", en: "Somalia", flag: "🇸🇴" },
  { code: "KE", it: "Kenya", en: "Kenya", flag: "🇰🇪" },
  { code: "UG", it: "Uganda", en: "Uganda", flag: "🇺🇬" },
  { code: "TZ", it: "Tanzania", en: "Tanzania", flag: "🇹🇿" },
  { code: "RW", it: "Ruanda", en: "Rwanda", flag: "🇷🇼" },
  { code: "BI", it: "Burundi", en: "Burundi", flag: "🇧🇮" },
  { code: "SS", it: "Sud Sudan", en: "South Sudan", flag: "🇸🇸" },
  // ── Africa meridionale ──
  { code: "ZA", it: "Sudafrica", en: "South Africa", flag: "🇿🇦" },
  { code: "NA", it: "Namibia", en: "Namibia", flag: "🇳🇦" },
  { code: "BW", it: "Botswana", en: "Botswana", flag: "🇧🇼" },
  { code: "ZW", it: "Zimbabwe", en: "Zimbabwe", flag: "🇿🇼" },
  { code: "MZ", it: "Mozambico", en: "Mozambique", flag: "🇲🇿" },
  { code: "MW", it: "Malawi", en: "Malawi", flag: "🇲🇼" },
  { code: "MG", it: "Madagascar", en: "Madagascar", flag: "🇲🇬" },
  { code: "LS", it: "Lesotho", en: "Lesotho", flag: "🇱🇸" },
  { code: "SZ", it: "eSwatini", en: "Eswatini", flag: "🇸🇿" },
  { code: "KM", it: "Comore", en: "Comoros", flag: "🇰🇲" },
  { code: "MU", it: "Mauritius", en: "Mauritius", flag: "🇲🇺" },
  { code: "SC", it: "Seychelles", en: "Seychelles", flag: "🇸🇨" },
  // ── Medio Oriente ──
  { code: "TR", it: "Turchia", en: "Turkey", flag: "🇹🇷" },
  { code: "IL", it: "Israele", en: "Israel", flag: "🇮🇱" },
  { code: "PS", it: "Palestina", en: "Palestine", flag: "🇵🇸" },
  { code: "JO", it: "Giordania", en: "Jordan", flag: "🇯🇴" },
  { code: "LB", it: "Libano", en: "Lebanon", flag: "🇱🇧" },
  { code: "SY", it: "Siria", en: "Syria", flag: "🇸🇾" },
  { code: "IQ", it: "Iraq", en: "Iraq", flag: "🇮🇶" },
  { code: "IR", it: "Iran", en: "Iran", flag: "🇮🇷" },
  { code: "SA", it: "Arabia Saudita", en: "Saudi Arabia", flag: "🇸🇦" },
  { code: "YE", it: "Yemen", en: "Yemen", flag: "🇾🇪" },
  { code: "OM", it: "Oman", en: "Oman", flag: "🇴🇲" },
  { code: "AE", it: "Emirati Arabi Uniti", en: "United Arab Emirates", flag: "🇦🇪" },
  { code: "QA", it: "Qatar", en: "Qatar", flag: "🇶🇦" },
  { code: "BH", it: "Bahrain", en: "Bahrain", flag: "🇧🇭" },
  { code: "KW", it: "Kuwait", en: "Kuwait", flag: "🇰🇼" },
  // ── Asia centrale / Caucaso ──
  { code: "KZ", it: "Kazakistan", en: "Kazakhstan", flag: "🇰🇿" },
  { code: "KG", it: "Kirghizistan", en: "Kyrgyzstan", flag: "🇰🇬" },
  { code: "UZ", it: "Uzbekistan", en: "Uzbekistan", flag: "🇺🇿" },
  { code: "TJ", it: "Tagikistan", en: "Tajikistan", flag: "🇹🇯" },
  { code: "TM", it: "Turkmenistan", en: "Turkmenistan", flag: "🇹🇲" },
  { code: "GE", it: "Georgia", en: "Georgia", flag: "🇬🇪" },
  { code: "AM", it: "Armenia", en: "Armenia", flag: "🇦🇲" },
  { code: "AZ", it: "Azerbaigian", en: "Azerbaijan", flag: "🇦🇿" },
  // ── Asia meridionale ──
  { code: "IN", it: "India", en: "India", flag: "🇮🇳" },
  { code: "PK", it: "Pakistan", en: "Pakistan", flag: "🇵🇰" },
  { code: "BD", it: "Bangladesh", en: "Bangladesh", flag: "🇧🇩" },
  { code: "AF", it: "Afghanistan", en: "Afghanistan", flag: "🇦🇫" },
  { code: "LK", it: "Sri Lanka", en: "Sri Lanka", flag: "🇱🇰" },
  { code: "NP", it: "Nepal", en: "Nepal", flag: "🇳🇵" },
  { code: "BT", it: "Bhutan", en: "Bhutan", flag: "🇧🇹" },
  { code: "MV", it: "Maldive", en: "Maldives", flag: "🇲🇻" },
  // ── Asia orientale ──
  { code: "CN", it: "Cina", en: "China", flag: "🇨🇳" },
  { code: "JP", it: "Giappone", en: "Japan", flag: "🇯🇵" },
  { code: "KR", it: "Corea del Sud", en: "South Korea", flag: "🇰🇷" },
  { code: "KP", it: "Corea del Nord", en: "North Korea", flag: "🇰🇵" },
  { code: "TW", it: "Taiwan", en: "Taiwan", flag: "🇹🇼" },
  { code: "MN", it: "Mongolia", en: "Mongolia", flag: "🇲🇳" },
  // ── Sud-est asiatico ──
  { code: "MM", it: "Myanmar", en: "Myanmar", flag: "🇲🇲" },
  { code: "TH", it: "Thailandia", en: "Thailand", flag: "🇹🇭" },
  { code: "LA", it: "Laos", en: "Laos", flag: "🇱🇦" },
  { code: "VN", it: "Vietnam", en: "Vietnam", flag: "🇻🇳" },
  { code: "KH", it: "Cambogia", en: "Cambodia", flag: "🇰🇭" },
  { code: "ID", it: "Indonesia", en: "Indonesia", flag: "🇮🇩" },
  { code: "MY", it: "Malesia", en: "Malaysia", flag: "🇲🇾" },
  { code: "SG", it: "Singapore", en: "Singapore", flag: "🇸🇬" },
  { code: "PH", it: "Filippine", en: "Philippines", flag: "🇵🇭" },
  { code: "BN", it: "Brunei", en: "Brunei", flag: "🇧🇳" },
  { code: "TL", it: "Timor Est", en: "East Timor", flag: "🇹🇱" },
  // ── Oceania ──
  { code: "AU", it: "Australia", en: "Australia", flag: "🇦🇺" },
  { code: "NZ", it: "Nuova Zelanda", en: "New Zealand", flag: "🇳🇿" },
  { code: "PG", it: "Papua Nuova Guinea", en: "Papua New Guinea", flag: "🇵🇬" },
  { code: "FJ", it: "Figi", en: "Fiji", flag: "🇫🇯" },
  { code: "SB", it: "Isole Salomone", en: "Solomon Islands", flag: "🇸🇧" },
  { code: "VU", it: "Vanuatu", en: "Vanuatu", flag: "🇻🇺" },
  { code: "WS", it: "Samoa", en: "Samoa", flag: "🇼🇸" },
  { code: "KI", it: "Kiribati", en: "Kiribati", flag: "🇰🇮" },
  { code: "TO", it: "Tonga", en: "Tonga", flag: "🇹🇴" },
  { code: "FM", it: "Micronesia", en: "Micronesia", flag: "🇫🇲" },
  { code: "MH", it: "Isole Marshall", en: "Marshall Islands", flag: "🇲🇭" },
  { code: "PW", it: "Palau", en: "Palau", flag: "🇵🇼" },
  { code: "NR", it: "Nauru", en: "Nauru", flag: "🇳🇷" },
  { code: "TV", it: "Tuvalu", en: "Tuvalu", flag: "🇹🇻" },
];

export const SITUATIONS = [
  { value: "lavoro", it: "💼 Lavoro", en: "💼 Work", fr: "💼 Travail", es: "💼 Trabajo", ar: "💼 عمل" },
  { value: "studio", it: "🎓 Studio", en: "🎓 Study", fr: "🎓 Études", es: "🎓 Estudio", ar: "🎓 دراسة" },
  { value: "famiglia", it: "👨‍👩‍👧 Famiglia", en: "👨‍👩‍👧 Family", fr: "👨‍👩‍👧 Famille", es: "👨‍👩‍👧 Familia", ar: "👨‍👩‍👧 لم شمل" },
  { value: "rinnovo", it: "🔄 Rinnovo", en: "🔄 Renewal", fr: "🔄 Renouvellement", es: "🔄 Renovación", ar: "🔄 تجديد" },
  { value: "altro", it: "ℹ️ Altro", en: "ℹ️ Other", fr: "ℹ️ Autre", es: "ℹ️ Otro", ar: "ℹ️ آخر" },
];

export function countryName(
  c: (typeof COUNTRIES)[number] | { code?: string; it?: string; en?: string; flag?: string } | undefined,
  lang: string
): string {
  if (!c) return "";
  const it = (c as any).it || (c as any).name || "";
  const en = (c as any).en || it;
  return (lang === "it" || lang === "ar" || lang === "fr" || lang === "es" ? it : en) || it || en || "";
}
