export const COUNTRIES = [
  { code: "IT", it: "Italia", en: "Italy", flag: "🇮🇹" },
  { code: "FR", it: "Francia", en: "France", flag: "🇫🇷" },
  { code: "DE", it: "Germania", en: "Germany", flag: "🇩🇪" },
  { code: "ES", it: "Spagna", en: "Spain", flag: "🇪🇸" },
  { code: "PT", it: "Portogallo", en: "Portugal", flag: "🇵🇹" },
  { code: "CH", it: "Svizzera", en: "Switzerland", flag: "🇨🇭" },
  { code: "AT", it: "Austria", en: "Austria", flag: "🇦🇹" },
  { code: "BE", it: "Belgio", en: "Belgium", flag: "🇧🇪" },
  { code: "NL", it: "Paesi Bassi", en: "Netherlands", flag: "🇳🇱" },
  { code: "SE", it: "Svezia", en: "Sweden", flag: "🇸🇪" },
  { code: "GB", it: "Regno Unito", en: "United Kingdom", flag: "🇬🇧" },
  { code: "IE", it: "Irlanda", en: "Ireland", flag: "🇮🇪" },
  { code: "US", it: "Stati Uniti", en: "United States", flag: "🇺🇸" },
  { code: "CA", it: "Canada", en: "Canada", flag: "🇨🇦" },
  { code: "AU", it: "Australia", en: "Australia", flag: "🇦🇺" },
  { code: "MA", it: "Marocco", en: "Morocco", flag: "🇲🇦" },
  { code: "DZ", it: "Algeria", en: "Algeria", flag: "🇩🇿" },
  { code: "TN", it: "Tunisia", en: "Tunisia", flag: "🇹🇳" },
  { code: "EG", it: "Egitto", en: "Egypt", flag: "🇪🇬" },
  { code: "SN", it: "Senegal", en: "Senegal", flag: "🇸🇳" },
  { code: "NG", it: "Nigeria", en: "Nigeria", flag: "🇳🇬" },
  { code: "GH", it: "Ghana", en: "Ghana", flag: "🇬🇭" },
  { code: "KE", it: "Kenya", en: "Kenya", flag: "🇰🇪" },
  { code: "BD", it: "Bangladesh", en: "Bangladesh", flag: "🇧🇩" },
  { code: "PK", it: "Pakistan", en: "Pakistan", flag: "🇵🇰" },
  { code: "IN", it: "India", en: "India", flag: "🇮🇳" },
  { code: "CN", it: "Cina", en: "China", flag: "🇨🇳" },
  { code: "UA", it: "Ucraina", en: "Ukraine", flag: "🇺🇦" },
  { code: "RU", it: "Russia", en: "Russia", flag: "🇷🇺" },
  { code: "TR", it: "Turchia", en: "Turkey", flag: "🇹🇷" },
  { code: "BR", it: "Brasile", en: "Brazil", flag: "🇧🇷" },
  { code: "AR", it: "Argentina", en: "Argentina", flag: "🇦🇷" },
  { code: "CO", it: "Colombia", en: "Colombia", flag: "🇨🇴" },
  { code: "VE", it: "Venezuela", en: "Venezuela", flag: "🇻🇪" },
  { code: "PH", it: "Filippine", en: "Philippines", flag: "🇵🇭" },
  { code: "SV", it: "El Salvador", en: "El Salvador", flag: "🇸🇻" },
  { code: "HN", it: "Honduras", en: "Honduras", flag: "🇭🇳" },
  { code: "GT", it: "Guatemala", en: "Guatemala", flag: "🇬🇹" },
  { code: "MX", it: "Messico", en: "Mexico", flag: "🇲🇽" },
  { code: "ZA", it: "Sudafrica", en: "South Africa", flag: "🇿🇦" },
  { code: "KR", it: "Corea del Sud", en: "South Korea", flag: "🇰🇷" },
  { code: "JP", it: "Giappone", en: "Japan", flag: "🇯🇵" },
  { code: "NO", it: "Norvegia", en: "Norway", flag: "🇳🇴" },
  { code: "DK", it: "Danimarca", en: "Denmark", flag: "🇩🇰" },
  { code: "FI", it: "Finlandia", en: "Finland", flag: "🇫🇮" },
  { code: "PL", it: "Polonia", en: "Poland", flag: "🇵🇱" },
  { code: "CZ", it: "Repubblica Ceca", en: "Czech Republic", flag: "🇨🇿" },
  { code: "HU", it: "Ungheria", en: "Hungary", flag: "🇭🇺" },
  { code: "RO", it: "Romania", en: "Romania", flag: "🇷🇴" },
  { code: "BG", it: "Bulgaria", en: "Bulgaria", flag: "🇧🇬" },
  { code: "GR", it: "Grecia", en: "Greece", flag: "🇬🇷" },
  { code: "HR", it: "Croazia", en: "Croatia", flag: "🇭🇷" },
  { code: "RS", it: "Serbia", en: "Serbia", flag: "🇷🇸" },
  { code: "AL", it: "Albania", en: "Albania", flag: "🇦🇱" },
  { code: "MD", it: "Moldavia", en: "Moldova", flag: "🇲🇩" },
  { code: "BY", it: "Bielorussia", en: "Belarus", flag: "🇧🇾" },
  { code: "KG", it: "Kirghizistan", en: "Kyrgyzstan", flag: "🇰🇬" },
  { code: "UZ", it: "Uzbekistan", en: "Uzbekistan", flag: "🇺🇿" },
  { code: "KZ", it: "Kazakistan", en: "Kazakhstan", flag: "🇰🇿" },
  { code: "IR", it: "Iran", en: "Iran", flag: "🇮🇷" },
  { code: "IQ", it: "Iraq", en: "Iraq", flag: "🇮🇶" },
  { code: "SY", it: "Siria", en: "Syria", flag: "🇸🇾" },
  { code: "SO", it: "Somalia", en: "Somalia", flag: "🇸🇴" },
  { code: "AF", it: "Afghanistan", en: "Afghanistan", flag: "🇦🇫" },
  { code: "MM", it: "Myanmar", en: "Myanmar", flag: "🇲🇲" },
  { code: "VN", it: "Vietnam", en: "Vietnam", flag: "🇻🇳" },
  { code: "LA", it: "Laos", en: "Laos", flag: "🇱🇦" },
  { code: "KH", it: "Cambogia", en: "Cambodia", flag: "🇰🇭" },
  { code: "ID", it: "Indonesia", en: "Indonesia", flag: "🇮🇩" },
  { code: "MY", it: "Malesia", en: "Malaysia", flag: "🇲🇾" },
  { code: "TH", it: "Thailandia", en: "Thailand", flag: "🇹🇭" },
  { code: "LK", it: "Sri Lanka", en: "Sri Lanka", flag: "🇱🇰" },
  { code: "NP", it: "Nepal", en: "Nepal", flag: "🇳🇵" },
  { code: "BT", it: "Bhutan", en: "Bhutan", flag: "🇧🇹" },
  { code: "MN", it: "Mongolia", en: "Mongolia", flag: "🇲🇳" },
  { code: "NZ", it: "Nuova Zelanda", en: "New Zealand", flag: "🇳🇿" },
  { code: "CL", it: "Cile", en: "Chile", flag: "🇨🇱" },
  { code: "PE", it: "Perù", en: "Peru", flag: "🇵🇪" },
  { code: "EC", it: "Ecuador", en: "Ecuador", flag: "🇪🇨" },
  { code: "UY", it: "Uruguay", en: "Uruguay", flag: "🇺🇾" },
  { code: "PY", it: "Paraguay", en: "Paraguay", flag: "🇵🇾" },
  { code: "BO", it: "Bolivia", en: "Bolivia", flag: "🇧🇴" },
  { code: "GY", it: "Guyana", en: "Guyana", flag: "🇬🇾" },
  { code: "SR", it: "Suriname", en: "Suriname", flag: "🇸🇷" },
  { code: "TT", it: "Trinidad e Tobago", en: "Trinidad and Tobago", flag: "🇹🇹" },
];

export const SITUATIONS = [
  { value: "lavoro", it: "💼 Lavoro", en: "💼 Work", fr: "💼 Travail", es: "💼 Trabajo", ar: "💼 عمل" },
  { value: "studio", it: "🎓 Studio", en: "🎓 Study", fr: "🎓 Études", es: "🎓 Estudio", ar: "🎓 دراسة" },
  { value: "famiglia", it: "👨‍👩‍👧 Famiglia", en: "👨‍👩‍👧 Family", fr: "👨‍👩‍👧 Famille", es: "👨‍👩‍👧 Familia", ar: "👨‍👩‍👧 لم شمل" },
  { value: "rinnovo", it: "🔄 Rinnovo", en: "🔄 Renewal", fr: "🔄 Renouvellement", es: "🔄 Renovación", ar: "🔄 تجديد" },
  { value: "altro", it: "ℹ️ Altro", en: "ℹ️ Other", fr: "ℹ️ Autre", es: "ℹ️ Otro", ar: "ℹ️ آخر" },
];

export function countryName(
  c: (typeof COUNTRIES)[number] | { code?: string; it?: string; en?: string; flag?: string } | undefined,
  lang: string
): string {
  if (!c) return "";
  const it = (c as any).it || (c as any).name || "";
  const en = (c as any).en || it;
  return (lang === "it" || lang === "ar" || lang === "fr" || lang === "es" ? it : en) || it || en || "";
}
